apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd-helm
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: helm/quarkus-helm
    repoURL: https://github.com/crossvale-inc/ocp-pipelines
    targetRevision: master
    helm:
      releaseName: order-service-helm
      valueFiles:
      - /helm/test-order-service-values.yaml