- op: replace
  path: /metadata/name
  value: order-service-kustomize
- op: replace
  path: /spec/selector/matchLabels/app
  value: order-service-kustomize
- op: replace
  path: /spec/template/metadata/labels/app
  value: order-service-kustomize
- op: replace
  path: /spec/template/metadata/labels/deployment
  value: order-service-kustomize
