{
 "title": "Application Resource Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"mrivas-development\",deployment=\"order-service-kustomize\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{namespace=\"mrivas-development\", service=\"order-service-kustomize\"}) BY (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{namespace=\"mrivas-development\",container=\"quarkus\"}/http_server_requests_seconds_count{namespace=\"mrivas-development\",container=\"quarkus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Container Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container='quarkus',namespace='mrivas-development'}) BY (pod, namespace)/1000000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource='memory',container='quarkus',namespace='mrivas-development'}) BY (pod, namespace)/1000000",
     "legendFormat": "{{pod}} request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource='memory',container='quarkus',namespace='mrivas-development'}) BY (pod, namespace)/1000000",
     "legendFormat": "{{pod}} limit"
    }
   ]
  },
  {
   "title": "Total Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~\"order-service-kustomize.*\",namespace='mrivas-development'}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'order-service-kustomize.*',namespace='mrivas-development'}) BY (pod, namespace)",
     "legendFormat": "{{pod}} request"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'order-service-kustomize.*',namespace='mrivas-development'}) BY (pod, namespace)",
     "legendFormat": "{{pod}} limit"
    }
   ]
  }
 ]
}