apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: quarkus-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: quarkus-service
    spec:
      containers:
      - image: quarkus-container-image
        imagePullPolicy: Always
        name: quarkus
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30