# Default values for quarkus-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/develop/order-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
